### ISSUE TITLE
게시글 페이지에서만 toc.js 동작하도록 수정

### ISSUE THREAD

**Issue by zineeworld** [wbluke/tistory-table-of-contents#7]
![image](https://user-images.githubusercontent.com/12759765/89665187-3e3ccf00-d913-11ea-82bf-6311e0ce61d7.png)

**Comment by zineeworld** [comment]
if ( document.querySelector('body').id === 'tt-body-page' ) { 
...
}

어딘가 글 페이지인지 아닌지 체크하는 게 있으면 에러가 안 생길 것 같아요.

**Comment by wbluke** [comment]
안녕하세요~ 올려주신 해당 100라인 에러의 존재성 체크 방식을 변경해서
`mainContents`가 null 일 경우 H 태그들을 빈 리스트로 대체하도록 수정하였습니다. (v0.1.6)

그리고 toc.js 최상단에 있는 `CLASS_OF_MAIN_CONTENTS` 클래스를 README.md 설명 참조하여 한번 확인 부탁드릴게요 :)
감사합니다!ㅎㅎ
